apiVersion: backblaze.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  # Backblaze B2 region where resources should be created
  # Common regions: us-west-001, us-west-002, eu-central-003
  backblazeRegion: us-west-001
  
  # Optional: Custom endpoint URL for Backblaze B2 S3-compatible API
  # If not specified, defaults to https://s3.{region}.backblazeb2.com
  # endpointURL: https://s3.us-west-001.backblazeb2.com
  
  credentials:
    source: Secret
    apiSecretRef:
      namespace: crossplane-system
      name: backblaze-creds
---
apiVersion: v1
kind: Secret
metadata:
  name: backblaze-creds
  namespace: crossplane-system
type: Opaque
data:
  # Base64 encoded Backblaze B2 Application Key ID
  # Get this from: Backblaze console -> App Keys -> Create Application Key
  applicationKeyId: <base64-encoded-key-id>
  
  # Base64 encoded Backblaze B2 Application Key  
  # This is the secret key associated with the Application Key ID above
  applicationKey: <base64-encoded-application-key>